# Request
mrs_inspector/InspectionPoint[] points
uint32[] uav_ids
float32 safety_distance
float32 inspection_distance # Distance from the UAV to the inspection point
float32 dt # Time step for trajectories
float32 stop_duration # Time to stop at each inspection point
bool return_to_start # Return to the starting point after the inspection
---
# Result
bool success
---
# Progress
float32 progress